services:
  recorder:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: "rtsp_recorder"
    env_file:
      - .env
    volumes:
      - "$OUTPUT_DIR:$OUTPUT_DIR"
      - "./:/app"
    working_dir: "/app"
    restart: unless-stopped